### ISSUE TITLE
Willing to be an Emacs buddy

### ISSUE THREAD

**Issue by yantar92** [ag91/emacs-buddy#11]
This project has been on my radar for a while now.

I think I can try to be a buddy an see how this works. I mostly use Org mode :)

Is there anything in particular I need to do?

**Comment by ag91** [comment]
amazing, thanks for your availability! If you could open a PR with a minimal description of you, that would be great. You can refer to the README of this project for examples. Otherwise just ping me the details at my email andrea-dev@hotmail.com and I can push a commit for you.

By the way any chance you use Gnus for emails? I am following an user with that but I don't use it myself (so basically referring to the manual XD)
